export const LOGIN = 'LOGIN';

export const SET_REPOSITORY_LIST = 'SET_REPOSITORY_LIST';
export const REPOSITORY_LOADING = 'REPOSITORY_LOADING';
export const SET_REPOSITORY_ISSUES = 'SET_REPOSITORY_ISSUES';